AWS_ACCESS_KEY: "AKIAXJ6RZW4R7M5ZDJHG"
AWS_SECRET_KEY: "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"
AWS_BUCKET: "flixter-sarosh"
AWS_REGION: "us-east-1"
SECRET_KEY: "sk_test_xbh6xm05qHKl5GwFpn67HSfq00oLBg44cy"
PUBLISHABLE_KEY: "pk_test_2wr32bDn3mUY4J9gqeoeaWNk00EEXHJjYu"